CREATE TABLE idea_machine_ideas (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  title TEXT NOT NULL,
  content TEXT,
  date_created TIMESTAMPTZ NOT NULL DEFAULT now(),
  date_modified TIMESTAMPTZ
);

ALTER TABLE idea_machine_ideas
  ADD COLUMN
    author_id INTEGER NOT NULL REFERENCES idea_machine_users(id) ON DELETE SET NULL;