CREATE TABLE idea_machine_followed_ideas (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY  
);

ALTER TABLE idea_machine_followed_ideas
ADD COLUMN
follower_id INTEGER REFERENCES idea_machine_users(id) ON DELETE CASCADE;

ALTER TABLE idea_machine_followed_ideas
ADD COLUMN
idea_id INTEGER REFERENCES idea_machine_ideas(id) ON DELETE CASCADE;

